/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 * @author Paul Idrovo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        mitInicioSesion = new javax.swing.JMenuItem();
        mitFinalizarSesion = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        mitAsignarCurso = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mitAgregarAlumno = new javax.swing.JMenuItem();
        mitCrearActividad = new javax.swing.JMenuItem();
        mitVerCursos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu1.setMnemonic('f');
        fileMenu1.setText("LOGIN");

        mitInicioSesion.setMnemonic('o');
        mitInicioSesion.setText("Iniciar Sesion");
        fileMenu1.add(mitInicioSesion);

        mitFinalizarSesion.setMnemonic('s');
        mitFinalizarSesion.setText("Finalizar Sesion");
        fileMenu1.add(mitFinalizarSesion);

        menuBar.add(fileMenu1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("RECTOR");

        mitAsignarCurso.setMnemonic('x');
        mitAsignarCurso.setText("Administrar");
        mitAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAsignarCursoActionPerformed(evt);
            }
        });
        fileMenu.add(mitAsignarCurso);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("DOCENTE");

        mitAgregarAlumno.setMnemonic('t');
        mitAgregarAlumno.setText("Agregar Alumno");
        editMenu.add(mitAgregarAlumno);

        mitCrearActividad.setMnemonic('y');
        mitCrearActividad.setText("Crear Actividad");
        editMenu.add(mitCrearActividad);

        mitVerCursos.setMnemonic('p');
        mitVerCursos.setText("Ver Curso");
        editMenu.add(mitVerCursos);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAsignarCursoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitAsignarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitAgregarAlumno;
    private javax.swing.JMenuItem mitAsignarCurso;
    private javax.swing.JMenuItem mitCrearActividad;
    private javax.swing.JMenuItem mitFinalizarSesion;
    private javax.swing.JMenuItem mitInicioSesion;
    private javax.swing.JMenuItem mitVerCursos;
    // End of variables declaration//GEN-END:variables

}
