/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorActividad;
import ec.edu.ups.controlador.ControladorEstudiante;
import ec.edu.ups.modelo.Actividad;
import ec.edu.ups.modelo.Estudiante;
import ec.edu.ups.modelo.ExpresionRegular;
import ec.edu.ups.modelo.ValidarSesion;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul Idrovo
 */
public class VistaAdministarDocente extends javax.swing.JInternalFrame {

    private ControladorEstudiante controladorEstudiante;
    private ControladorActividad controladorActividad;
    ValidarSesion sesionIniciado;

    public VistaAdministarDocente() {
        initComponents();
        controladorEstudiante = new ControladorEstudiante();
        controladorActividad = new ControladorActividad();
        sesionIniciado = ValidarSesion.getValidarSesion(0, 0, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnGuardarAlumno = new javax.swing.JButton();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreActividad = new javax.swing.JTextField();
        btnGuardarActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        cmbActividad = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btnCargarActividad = new javax.swing.JButton();
        btnActualizarActividad = new javax.swing.JButton();
        btnAgregarNuevosParametros = new javax.swing.JButton();
        lblIdA = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("AGREGAR ALUMNO"));

        jLabel7.setText("CEDULA");

        jLabel8.setText("NOMBRE");

        jLabel9.setText("APELLIDO");

        jLabel10.setText("DIRECCION");

        jLabel11.setText("GENERO");

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GENERO", "MASCULINO", "FEMENINO" }));

        jLabel12.setText("F. NACIMIENTO");

        btnGuardarAlumno.setText("GUARDAR");
        btnGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumnoActionPerformed(evt);
            }
        });

        dcFechaNacimiento.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbGenero, 0, 251, Short.MAX_VALUE)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtApellido)
                                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnGuardarAlumno)))
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnGuardarAlumno)
                .addGap(10, 10, 10))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("ACTIVIDAD"));

        jLabel19.setText("NOMBRE ACTIVIDAD");

        btnGuardarActividad.setText("GUARDAR");
        btnGuardarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addGap(25, 25, 25)
                .addComponent(txtNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnGuardarActividad)
                .addGap(164, 164, 164))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnGuardarActividad)
                .addContainerGap())
        );

        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CEDULA", "NOMBRE", "APELLIDO", "DIRECCION", "F. NACIMIENTO", "GENERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumno);
        if (tblAlumno.getColumnModel().getColumnCount() > 0) {
            tblAlumno.getColumnModel().getColumn(0).setMinWidth(80);
            tblAlumno.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAlumno.getColumnModel().getColumn(0).setMaxWidth(140);
        }

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "TITULO", "LINK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblActividades);
        if (tblActividades.getColumnModel().getColumnCount() > 0) {
            tblActividades.getColumnModel().getColumn(0).setMinWidth(80);
            tblActividades.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblActividades.getColumnModel().getColumn(0).setMaxWidth(140);
            tblActividades.getColumnModel().getColumn(1).setMinWidth(150);
            tblActividades.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblActividades.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        cmbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR ACTIVIDAD" }));

        jLabel25.setText("SELEC. ACTIVIDAD");

        btnCargarActividad.setText("CARGAR");
        btnCargarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActividadActionPerformed(evt);
            }
        });

        btnActualizarActividad.setText("ACTUALIZAR");
        btnActualizarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActividadActionPerformed(evt);
            }
        });

        btnAgregarNuevosParametros.setText("GUARDAR");
        btnAgregarNuevosParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevosParametrosActionPerformed(evt);
            }
        });

        lblIdA.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdA)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(35, 35, 35)
                                .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCargarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(btnActualizarActividad)
                                .addGap(81, 81, 81)
                                .addComponent(btnAgregarNuevosParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel25))
                            .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCargarActividad)
                                .addComponent(lblIdA))
                            .addComponent(btnActualizarActividad)
                            .addComponent(btnAgregarNuevosParametros))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnoActionPerformed
        ExpresionRegular ex = new ExpresionRegular();
        ExpresionRegular exNombre = new ExpresionRegular();
        ex.ingresarRegex("^\\d{10}");
        exNombre.ingresarRegex("^\\w+$");
        if (dcFechaNacimiento.getDate() == null) {
            JOptionPane.showMessageDialog(null, "FORMATO DE FECHA NO VALIDA", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        } else if (!ex.validar(txtCedula.getText())) {
            JOptionPane.showMessageDialog(null, "CEDULA NO VALIDA", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        } else if (!exNombre.validar(txtNombre.getText()) || !exNombre.validar(txtApellido.getText())) {
            JOptionPane.showMessageDialog(null, "NOMBRE Y/O APELLIDO NO VALIDO NO DEBEN CONTENER ESPACIOS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        } else {
            java.sql.Date fechaSql = java.sql.Date.valueOf(dcFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            controladorEstudiante.crear(new Estudiante(sesionIniciado.getCurso(), txtCedula.getText(), txtNombre.getText(), txtApellido.getText(), txtDireccion.getText(), fechaSql, cmbGenero.getSelectedItem().toString()));
            cargarEstudiantes();
            limpiarDatosEstudiante();
        }
    }//GEN-LAST:event_btnGuardarAlumnoActionPerformed

    private void btnGuardarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActividadActionPerformed
        controladorActividad.crear(new Actividad(sesionIniciado.getCurso(), txtNombreActividad.getText()));
        cargarActividades();
        txtNombreActividad.setText("");
    }//GEN-LAST:event_btnGuardarActividadActionPerformed

    private void btnCargarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActividadActionPerformed
        ExpresionRegular ex = new ExpresionRegular();
        ex.ingresarRegex("\\d+");
        if (ex.validar(cmbActividad.getSelectedItem().toString())) {
            lblIdA.setText(ex.obtenerId(cmbActividad.getSelectedItem().toString()) + "");
            cargarDatosAsignatura(ex.obtenerId(cmbActividad.getSelectedItem().toString()));
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA ACTIVIDAD", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarActividadActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        lblIdA.setVisible(false);
        cargarEstudiantes();
        cargarActividades();
        limpiarDatosEstudiante();
        txtNombreActividad.setText("");
        eliminarDatosActividadTabla();
    }//GEN-LAST:event_formInternalFrameActivated
    private void eliminarDatosActividadTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
        modelo.setRowCount(0);
        tblActividades.setModel(modelo);
    }
    private void btnActualizarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActividadActionPerformed
        JOptionPane.showMessageDialog(null, "REALIZANDO BUSQUEDA WEB - ESTO PUEDE TARDAR UNOS MINUTOS - PRESIONE APCETAR");
        eliminarDatosActividadTabla();
        ExpresionRegular ex = new ExpresionRegular();
        ExpresionRegular exUrl = new ExpresionRegular();
        ExpresionRegular exTitulo = new ExpresionRegular();
        //EXPRESIONES REGULARES
        ex.ingresarRegex("\\d+");
        lblIdA.setText(ex.obtenerId(cmbActividad.getSelectedItem().toString()) + "");
        ex.ingresarRegex("\\s{2}\\w+");
        exUrl.ingresarRegex("<a href=\\\"\\/store\\/apps\\/details\\?id=((\\w)+\\.?)+");
        exTitulo.ingresarRegex("title\">(\\w+\\s?:?\\s?)+");

        if (ex.validar(cmbActividad.getSelectedItem().toString())) {
            String url = ex.obtenerTexto(cmbActividad.getSelectedItem().toString());
            url = url.replace("  ", "").replaceAll("\\s", "\\%20");
            url = "https://play.google.com/store/search?q=" + url + "&c=apps";
            StringBuilder stringBuilder = conexionURL(url);
            Set<String> resultado = exUrl.obtenerUrlGoogle(stringBuilder.toString());
            DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
            modelo.setRowCount(0);
            tblActividades.setModel(modelo);
            Object[] fila = new Object[3];

            resultado.stream().map(link -> link.replace("<a href=\"", "https://play.google.com")).forEachOrdered(urlTitulo -> {
                StringBuilder stringBuildertTitulo = conexionURL(urlTitulo);
                String titulo = exTitulo.obtenertitulo(stringBuildertTitulo.toString());
                fila[0] = "N/A";
                fila[1] = titulo.replace("title\">", "");
                fila[2] = urlTitulo;
                modelo.addRow(fila);
            });
            this.tblActividades.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA ACTIVIDAD", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActividadActionPerformed

    private void btnAgregarNuevosParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevosParametrosActionPerformed
        int numFilas = tblActividades.getRowCount();
        List<Actividad> listaDatosActividades = new ArrayList<>();
        for (int i = 0; i < numFilas; i++) {
            listaDatosActividades.add(new Actividad(Integer.parseInt(lblIdA.getText()), tblActividades.getValueAt(i, 1).toString(), tblActividades.getValueAt(i, 2).toString()));
        }
        controladorActividad.GuardarDatos(listaDatosActividades);
        eliminarDatosActividadTabla();
        JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS");

    }//GEN-LAST:event_btnAgregarNuevosParametrosActionPerformed

    private void cargarEstudiantes() {
        DefaultTableModel modelo = (DefaultTableModel) tblAlumno.getModel();
        modelo.setRowCount(0);
        tblAlumno.setModel(modelo);
        Object[] fila = new Object[7];
        controladorEstudiante.listaEstudiantes(sesionIniciado.getCurso()).stream().map(estudiante -> {
            fila[0] = estudiante.getId();
            return estudiante;
        }).map(estudiante -> {
            fila[1] = estudiante.getCedula();
            return estudiante;
        }).map(estudiante -> {
            fila[2] = estudiante.getNombre();
            return estudiante;
        }).map(estudiante -> {
            fila[3] = estudiante.getApellido();
            return estudiante;
        }).map(estudiante -> {
            fila[4] = estudiante.getDireccion();
            return estudiante;
        }).map(estudiante -> {
            fila[5] = estudiante.getFecha();
            return estudiante;
        }).map(estudiante -> {
            fila[6] = estudiante.getGenero();
            return estudiante;
        }).forEachOrdered(_item -> {
            modelo.addRow(fila);
        });
        this.tblAlumno.setModel(modelo);
        //controladorEstudiante
    }

    private void cargarDatosAsignatura(int actividadId) {
        DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
        modelo.setRowCount(0);
        tblActividades.setModel(modelo);
        Object[] fila = new Object[7];
        controladorActividad.listaDatosActividades(actividadId).stream().map(datosActividad -> {
            fila[0] = datosActividad.getId();
            return datosActividad;
        }).map(datosActividad -> {
            fila[1] = datosActividad.getTema();
            return datosActividad;
        }).map(datosActividad -> {
            fila[2] = datosActividad.getLink();
            return datosActividad;
        }).forEachOrdered(_item -> {
            modelo.addRow(fila);
        });
        this.tblActividades.setModel(modelo);
    }

    private void limpiarDatosEstudiante() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
    }

    private void cargarActividades() {
        cmbActividad.removeAllItems();
        cmbActividad.addItem("SELECIONAR ACTIVIDAD");
        controladorActividad.listaActividades(sesionIniciado.getCurso()).forEach(actividad -> {
            cmbActividad.addItem(actividad.getId() + " -  " + actividad.getTema());
        });
    }

    private StringBuilder conexionURL(String url) {
        StringBuilder stringBuilder = new StringBuilder();
        try {
            URL urlObject = new URL(url);
            URLConnection urlConnection = urlObject.openConnection();
            urlConnection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(urlConnection.getInputStream(), "UTF-8"));

            String inputLine;
            while ((inputLine = bufferedReader.readLine()) != null) {
                stringBuilder.append(inputLine);
            }
        } catch (FileNotFoundException ex) {

        } catch (MalformedURLException ex) {
            Logger.getLogger(VistaAdministarDocente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VistaAdministarDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
        return stringBuilder;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActividad;
    private javax.swing.JButton btnAgregarNuevosParametros;
    private javax.swing.JButton btnCargarActividad;
    private javax.swing.JButton btnGuardarActividad;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JComboBox<String> cmbActividad;
    private javax.swing.JComboBox<String> cmbGenero;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdA;
    private javax.swing.JTable tblActividades;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreActividad;
    // End of variables declaration//GEN-END:variables
}
