/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.ValidarSesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Idrovo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaAdministarDocente vistaAdministarDocente;
    private VistaAdministarRector vistaAdministarRector;
    private VistaInicioSesion vistaInicioSesion;

    public VistaPrincipal() {
        initComponents();
        vistaAdministarDocente = new VistaAdministarDocente();
        vistaAdministarRector = new VistaAdministarRector();
        vistaInicioSesion = new VistaInicioSesion();
        desktopPane.add(vistaInicioSesion);
        desktopPane.add(vistaAdministarDocente);
        desktopPane.add(vistaAdministarRector);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        mitInicioSesion = new javax.swing.JMenuItem();
        mitFinalizarSesion = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        mitAdministarRector = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mitAdministrarDocente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu1.setMnemonic('f');
        fileMenu1.setText("LOGIN");

        mitInicioSesion.setMnemonic('o');
        mitInicioSesion.setText("Iniciar Sesion");
        mitInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitInicioSesionActionPerformed(evt);
            }
        });
        fileMenu1.add(mitInicioSesion);

        mitFinalizarSesion.setMnemonic('s');
        mitFinalizarSesion.setText("Finalizar Sesion");
        mitFinalizarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitFinalizarSesionActionPerformed(evt);
            }
        });
        fileMenu1.add(mitFinalizarSesion);

        menuBar.add(fileMenu1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("RECTOR");

        mitAdministarRector.setMnemonic('x');
        mitAdministarRector.setText("Administrar");
        mitAdministarRector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAdministarRectorActionPerformed(evt);
            }
        });
        fileMenu.add(mitAdministarRector);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("DOCENTE");

        mitAdministrarDocente.setMnemonic('t');
        mitAdministrarDocente.setText("Administrar");
        mitAdministrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAdministrarDocenteActionPerformed(evt);
            }
        });
        editMenu.add(mitAdministrarDocente);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitAdministarRectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAdministarRectorActionPerformed
        ocultar();
        ValidarSesion vlSesion = ValidarSesion.getValidarSesion(0, 0, "");
        if (vlSesion.getRol().equals("RECTOR")) {
            vistaAdministarRector.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO TIENE PERMISOS PARA ESTA SECCION", "ACCESO DENEGADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mitAdministarRectorActionPerformed

    private void mitAdministrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAdministrarDocenteActionPerformed
        ocultar();
        ValidarSesion vlSesion = ValidarSesion.getValidarSesion(0, 0, " ");
        if (vlSesion.getRol().equals("DOCENTE")) {
            if (vlSesion.getCurso() != 0) {
                vistaAdministarDocente.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null, "NO TIENE CURSO ASIGNADO", "ACCESO DENEGADO", JOptionPane.WARNING_MESSAGE); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO TIENE PERMISOS PARA ESTA SECCION", "ACCESO DENEGADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mitAdministrarDocenteActionPerformed

    private void mitInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitInicioSesionActionPerformed
        ocultar();
        vistaInicioSesion.setVisible(true);
    }//GEN-LAST:event_mitInicioSesionActionPerformed

    private void mitFinalizarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitFinalizarSesionActionPerformed
        ocultar();
        ValidarSesion vlSesion = ValidarSesion.getValidarSesion(0, 0, "");
        vlSesion.setId(0);
        vlSesion.setCurso(0);
        vlSesion.setRol("");
        JOptionPane.showMessageDialog(null, "SESION FINALIZADA", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mitFinalizarSesionActionPerformed
    private void ocultar() {
        vistaAdministarDocente.setVisible(false);
        vistaAdministarRector.setVisible(false);
        vistaInicioSesion.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitAdministarRector;
    private javax.swing.JMenuItem mitAdministrarDocente;
    private javax.swing.JMenuItem mitFinalizarSesion;
    private javax.swing.JMenuItem mitInicioSesion;
    // End of variables declaration//GEN-END:variables

}
